# Deployment role for Laravel5 apps.
# Brought to you by Blacklight - http://www.blacklight.co.za/.
# Developer: Zander Janse van Rensburg <zjvren@geevcookie.com>
# License: MIT
#
# This file handles the creation of symlinks to the new release.
---
- name: Create .env symlink
  file: state=link src={{ laravel_root_dir }}/shared/.env path={{ laravel_root_dir }}/releases/{{ release_version.stdout }}/.env force=true

- name: Delete storage
  file: path={{ laravel_root_dir }}/releases/{{ release_version.stdout }}/storage state=absent
  register: storage_directory_deleted
  ignore_errors: true

- name: Create storage symlink
  file: state=link src={{ laravel_root_dir }}/shared/storage path={{ laravel_root_dir }}/releases/{{ release_version.stdout }}/storage
  when: storage_directory_deleted is success
  register: storage_symlink
  ignore_errors: true

- name: Create public storage symlink
  file: state=link src={{ laravel_root_dir }}/shared/storage/app/public path={{ laravel_root_dir }}/releases/{{ release_version.stdout }}/public/storage
  when: storage_symlink is success
  register: symlinks_created
  ignore_errors: true
